#!/bin/sh
set -e
if [ "$1" = install ] || [ "$1" = upgrade ]; then
    for f in /usr/bin/brave-browser-stable /usr/bin/brave-origin-stable; do
        dpkg-divert --package brave-flags-wrapper --add --rename \
            --divert "$f.original" "$f"
    done
fi
