#!/bin/sh
set -e

case "$1" in
	configure)

		# Reload udev rules and trigger events
		if command -v udevadm >/dev/null 2>&1; then
			udevadm control --reload || true
			udevadm trigger || true
		fi

		# Set io schedulers to kyber
		switch-io kyber || true

		# Reload systemd daemon
		if command -v systemctl >/dev/null 2>&1; then
			systemctl daemon-reload || true
		fi
        ;;
esac

exit 0
