#!/bin/sh
echo 1>&2 "Adding boot menu entry for Rescuezilla"
exec tail -n +4 $0

submenu "Rescuezilla" {

	insmod regexp
	insmod loopback

	for iso in /boot/iso/rescuezilla-*.iso; do

		# Prevent message when directory is empty
		if [ "${iso}" != "/boot/iso/rescuezilla-*.iso" ]; then

			regexp --set=iso_file '^/boot/iso/(.*$)' "$iso"
			menuentry "Boot: $iso_file" $iso{
				iso_path=$2
				export iso_path
				search --set=root --file $iso_path
				loopback loop $iso_path
				root=(loop)
				configfile /boot/grub/loopback.cfg
				loopback --delete loop
			}
		fi
	done
}

