#!/bin/sh
echo 1>&2 "Adding boot menu entry for Clonezilla"
exec tail -n +4 $0

submenu "Clonezilla" {

	insmod regexp
	insmod loopback

	for iso in /boot/iso/clonezilla-*.iso; do
	
		# Prevent message when directory is empty
		if [ "${iso}" != "/boot/iso/clonezilla-*.iso" ]; then

			regexp --set=iso_file '^/boot/iso/(.*$)' "$iso"
			submenu "Boot: $iso_file" $iso{

				isofile=$2

				menuentry --hotkey=R "Clonezilla live (KMS & To RAM)" {
					loopback loop $isofile
					linux (loop)/live/vmlinuz --- findiso=$isofile boot=live union=overlay username=user config components quiet noswap edd=on enforcing=0 locales= keyboard-layouts= ocs_live_run="ocs-live-general" ocs_live_extra_param="" ocs_live_batch="no" vga=791 toram=live,syslinux,EFI,boot,.disk,utils ip= net.ifnames=0  nosplash
					initrd (loop)/live/initrd.img
				}
				menuentry "Clonezilla live (KMS with large font & To RAM)" --id live-kms-large-font-toram {
					loopback loop $isofile
					linux (loop)/live/vmlinuz --- findiso=$isofile boot=live union=overlay username=user config components quiet noswap edd=on enforcing=0 locales= keyboard-layouts= ocs_live_run="ocs-live-general" ocs_live_extra_param="" ocs_live_batch="no" vga=791 toram=live,syslinux,EFI,boot,.disk,utils ip= net.ifnames=0  nosplash live_console_font_size=16x32
					initrd (loop)/live/initrd.img
				}
				menuentry --hotkey=r "Clonezilla live (VGA 800x600 & To RAM)" --id live-toram {
					loopback loop $isofile
					linux (loop)/live/vmlinuz --- findiso=$isofile boot=live union=overlay username=user config components quiet noswap edd=on nomodeset enforcing=0 locales= keyboard-layouts= ocs_live_run="ocs-live-general" ocs_live_extra_param="" ocs_live_batch="no" vga=788 toram=live,syslinux,EFI,boot,.disk,utils ip= net.ifnames=0  nosplash i915.blacklist=yes radeonhd.blacklist=yes nouveau.blacklist=yes vmwgfx.enable_fbdev=1
					initrd (loop)/live/initrd.img
				}
				menuentry --hotkey=l "Clonezilla live (VGA with large font & To RAM)" --id live-vga-large-font-toram {
					loopback loop $isofile
					linux (loop)/live/vmlinuz --- findiso=$isofile boot=live union=overlay username=user config components quiet noswap edd=on nomodeset enforcing=0 locales= keyboard-layouts= ocs_live_run="ocs-live-general" ocs_live_extra_param="" ocs_live_batch="no" nomodeset toram=live,syslinux,EFI,boot,.disk,utils ip= net.ifnames=0  nosplash live_console_font_size=16x32
					initrd (loop)/live/initrd.img
				}
			}
		fi
	done
}
