#!/bin/sh
echo 1>&2 "Adding boot menu entry for System, Power and UEFI Firmware"
exec tail -n +4 $0
#exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "System restart cold/hard (use CTRL-ALT-DEL for warm/soft reboot)" {
	echo "System rebooting..."
	reboot
}
menuentry "System shutdown" {
	echo "System shutting down..."
	halt
}
