Section "Device"
    Identifier    "Intel or AMD GPU"
    Driver        "modesetting"
    Option        "ShadowFB"         "false"   # you don't need on recent hardware
    Option        "Atomic"           "true"    # only effective on Xlibre, or Xorg-git with a special patch
    Option        "TearFree"         "true"
    Option        "VariableRefresh"  "true"
EndSection
